apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: samples.stable.example.com
spec:
  group: stable.example.com

  versions:
    - name: v1alpha
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object

  scope: Namespaced

  names:
    kind: Sample
    plural: samples
    singular: sample
    shortNames: ["sp"]
